import { ServiceOrder, AppNotification } from './types';

export const INITIAL_SERVICE_ORDERS: ServiceOrder[] = [
  {
    id: 'ord-101',
    caseNumber: 'CV-2026-08942',
    courtName: 'Superior Court of California, County of Los Angeles',
    plaintiff: 'Vanguard Global Capital Partners LLC',
    defendant: 'Arthur Sterling & Meridian Tech Holdings',
    hearingDate: '2026-10-18',
    documentTypes: [
      'Summons and Complaint',
      'Notice of Case Assignment',
      'Civil Case Cover Sheet',
      'Subpoena Duces Tecum'
    ],
    recipientName: 'Arthur Sterling',
    recipientPhone: '(310) 555-0149',
    serviceAddress: '1420 Ocean Avenue, Penthouse 4B, Santa Monica, CA 90401',
    alternateAddress: '9800 Wilshire Blvd, Suite 600, Beverly Hills, CA 90212',
    priority: 'same_day',
    status: 'served',
    specialInstructions: 'High-profile subject. Doorman building - state process server authority under CCP 415.21 for authorized entry. Target usually departs building around 7:45 AM.',
    clientName: 'Sarah Jenkins, Esq.',
    clientFirm: 'Jenkins & Sterling Litigation LLP',
    clientEmail: 'sjenkins@sterlinglit.com',
    clientPhone: '(213) 555-8830',
    assignedServerName: 'Marcus Vance',
    assignedServerPhone: '(310) 555-7291',
    createdAt: '2026-09-14T08:15:00Z',
    updatedAt: '2026-09-14T17:42:00Z',
    deadlineDate: '2026-09-15',
    proofOfServiceSignedAt: '2026-09-14T17:45:00Z',
    proofOfServiceSigner: 'Marcus Vance, Certified Server #LA-4991',
    attempts: [
      {
        id: 'att-101-1',
        orderId: 'ord-101',
        timestamp: '2026-09-14T11:20:00Z',
        outcome: 'resident_not_home',
        serverName: 'Marcus Vance',
        serverBadgeId: 'LA-4991',
        latitude: 34.0125,
        longitude: -118.4951,
        locationAddress: '1420 Ocean Avenue, Santa Monica, CA 90401',
        notes: 'Building concierge confirmed subject resides in PH-4B but had stepped out for lunch meeting. Advised server to return after 4:00 PM.',
        photoUrl: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=600&q=80',
        verifiedGps: true
      },
      {
        id: 'att-101-2',
        orderId: 'ord-101',
        timestamp: '2026-09-14T17:35:00Z',
        outcome: 'personal_service',
        serverName: 'Marcus Vance',
        serverBadgeId: 'LA-4991',
        latitude: 34.0126,
        longitude: -118.4952,
        locationAddress: '1420 Ocean Avenue, Santa Monica, CA 90401',
        recipientNameServed: 'Arthur Sterling',
        relationshipToRecipient: 'Self / Direct Subject',
        recipientDescription: {
          approxAge: '52',
          gender: 'Male',
          height: '6ft 1in',
          weight: '190 lbs',
          hairColor: 'Silver / Gray',
          wearsGlasses: true,
          distinguishingFeatures: 'Navy blazer, gold signet ring on right hand'
        },
        notes: 'Subject intercepted in primary building lobby while returning with mail. Stated name and confirmed identity. Handed complete document package directly. Subject accepted documents calmly.',
        photoUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=600&q=80',
        signatureUrl: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="160" height="40"><path d="M10 25 C 30 10, 50 35, 70 15 S 110 30, 140 18" stroke="%231e293b" stroke-width="2" fill="none"/></svg>',
        verifiedGps: true
      }
    ]
  },
  {
    id: 'ord-102',
    caseNumber: 'UD-2026-11409',
    courtName: 'Municipal Court of South Bay Judicial District',
    plaintiff: 'Pacific Crest Property Holdings LLC',
    defendant: 'Elena Rostova & All Other Occupants',
    hearingDate: '2026-09-29',
    documentTypes: [
      '3-Day Notice to Pay Rent or Quit',
      'Summons - Unlawful Detainer',
      'Complaint for Possession of Real Property'
    ],
    recipientName: 'Elena Rostova',
    recipientPhone: '(424) 555-0812',
    serviceAddress: '742 South Catalina Ave, Apt 12, Redondo Beach, CA 90277',
    priority: 'rush',
    status: 'in_progress',
    specialInstructions: 'Apartment on 2nd floor, exterior staircase on north side. Gated driveway code #1892. Client requests immediate notice if premises appear abandoned.',
    clientName: 'David K. Mendoza',
    clientFirm: 'Mendoza Property Group Management',
    clientEmail: 'dmendoza@pacificcrestholdings.com',
    clientPhone: '(310) 555-4300',
    assignedServerName: 'Elena Chen',
    assignedServerPhone: '(310) 555-9014',
    createdAt: '2026-09-13T14:30:00Z',
    updatedAt: '2026-09-14T19:10:00Z',
    deadlineDate: '2026-09-16',
    attempts: [
      {
        id: 'att-102-1',
        orderId: 'ord-102',
        timestamp: '2026-09-14T07:45:00Z',
        outcome: 'no_answer',
        serverName: 'Elena Chen',
        serverBadgeId: 'LA-5102',
        latitude: 33.8358,
        longitude: -118.3884,
        locationAddress: '742 S Catalina Ave, Apt 12, Redondo Beach, CA 90277',
        notes: 'Knocked and announced presence firmly 3 times. Lights on inside, dog barking, but no occupant answered the door. Left contact business card in doorway.',
        photoUrl: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=600&q=80',
        verifiedGps: true
      },
      {
        id: 'att-102-2',
        orderId: 'ord-102',
        timestamp: '2026-09-14T18:50:00Z',
        outcome: 'no_answer',
        serverName: 'Elena Chen',
        serverBadgeId: 'LA-5102',
        latitude: 33.8359,
        longitude: -118.3883,
        locationAddress: '742 S Catalina Ave, Apt 12, Redondo Beach, CA 90277',
        notes: 'Second attempt during evening hours. Vehicle with matching CA license plate in carport #12. Knocked on door; female voice asked "Who is it?", but when server stated legal process server delivery, occupant went silent and declined opening. Preparing for substituted service or posting order.',
        photoUrl: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=600&q=80',
        verifiedGps: true
      }
    ]
  },
  {
    id: 'ord-103',
    caseNumber: 'FAM-2026-04221',
    courtName: 'Superior Court of California, Family Law Division',
    plaintiff: 'Cynthia Marie Alvarez',
    defendant: 'Roberto Alvarez',
    hearingDate: '2026-10-05',
    documentTypes: [
      'Petition for Dissolution of Marriage',
      'Summons (Family Law)',
      'Income and Expense Declaration',
      'Child Custody & Visitation Application'
    ],
    recipientName: 'Roberto Alvarez',
    recipientPhone: '(562) 555-7311',
    serviceAddress: '3180 E Willow Street, Long Beach, CA 90806',
    alternateAddress: 'Alvarez Auto Body & Marine, 1201 W Anaheim St, Wilmington, CA',
    priority: 'rush',
    status: 'assigned',
    specialInstructions: 'Workplace service permitted if residence fails. Recipient works as shop foreman at auto body facility.',
    clientName: 'Rachel Thorne, Esq.',
    clientFirm: 'Thorne & Bay Family Law',
    clientEmail: 'rachel@thornefamilylaw.com',
    clientPhone: '(562) 555-1990',
    assignedServerName: 'Marcus Vance',
    assignedServerPhone: '(310) 555-7291',
    createdAt: '2026-09-14T16:00:00Z',
    updatedAt: '2026-09-14T16:20:00Z',
    deadlineDate: '2026-09-17',
    attempts: []
  },
  {
    id: 'ord-104',
    caseNumber: 'SC-2026-90184',
    courtName: 'Orange County Superior Court, Central Justice Center',
    plaintiff: 'Dr. Kimberly Walsh',
    defendant: 'BioHealth Diagnostic Laboratories Inc.',
    hearingDate: '2026-11-12',
    documentTypes: [
      'Subpoena for Production of Business Records',
      'Deposition Subpoena for Personal Appearance',
      'Notice to Consumer or Employee'
    ],
    recipientName: 'Custodian of Records, BioHealth Diagnostic Labs',
    serviceAddress: '400 Corporate Pointe, Suite 350, Irvine, CA 92618',
    priority: 'routine',
    status: 'served',
    specialInstructions: 'Service must be made directly on registered agent or designated records custodian. Witness fee check of $15.00 attached to subpoena package.',
    clientName: 'Marcus Bennett, Esq.',
    clientFirm: 'Bennett Trial Attorneys',
    clientEmail: 'mbennett@bennetttrial.com',
    clientPhone: '(949) 555-3211',
    assignedServerName: 'Elena Chen',
    assignedServerPhone: '(310) 555-9014',
    createdAt: '2026-09-11T10:00:00Z',
    updatedAt: '2026-09-12T14:15:00Z',
    deadlineDate: '2026-09-18',
    proofOfServiceSignedAt: '2026-09-12T14:30:00Z',
    proofOfServiceSigner: 'Elena Chen, Registered Process Server #OC-8821',
    attempts: [
      {
        id: 'att-104-1',
        orderId: 'ord-104',
        timestamp: '2026-09-12T13:45:00Z',
        outcome: 'substituted_service',
        serverName: 'Elena Chen',
        serverBadgeId: 'OC-8821',
        latitude: 33.6846,
        longitude: -117.8265,
        locationAddress: '400 Corporate Pointe, Suite 350, Irvine, CA 92618',
        recipientNameServed: 'Patricia Howell',
        relationshipToRecipient: 'Authorized Office Administrator / Records Manager',
        recipientDescription: {
          approxAge: '45',
          gender: 'Female',
          height: '5ft 6in',
          weight: '145 lbs',
          hairColor: 'Brown / Auburn',
          wearsGlasses: false,
          distinguishingFeatures: 'Corporate badge #B-108, business attire'
        },
        notes: 'Served designated corporate receiver authorized to accept legal service of process. Witness fee check #9841 tendered and accepted. Copy subsequently mailed per statutory procedure.',
        photoUrl: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=600&q=80',
        signatureUrl: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="160" height="40"><path d="M15 20 C 40 30, 60 5, 90 25 S 130 15, 145 22" stroke="%231e293b" stroke-width="2" fill="none"/></svg>',
        verifiedGps: true
      }
    ]
  },
  {
    id: 'ord-105',
    caseNumber: 'CV-2026-77821',
    courtName: 'San Diego County Superior Court',
    plaintiff: 'Highland Logistics Fleet Services',
    defendant: 'Vortex Freightliners LLC & Gary Miller',
    hearingDate: '2026-10-22',
    documentTypes: [
      'Summons & Complaint for Breach of Commercial Lease',
      'Prejudgment Claim of Right to Possession'
    ],
    recipientName: 'Gary Miller',
    recipientPhone: '(619) 555-8819',
    serviceAddress: '8840 Miramar Road, Unit 14B, San Diego, CA 92126',
    priority: 'routine',
    status: 'non_served',
    specialInstructions: 'Address listed on Secretary of State filing. Please confirm if business is still operating at location.',
    clientName: 'Gregory Soto',
    clientFirm: 'Highland Logistics Corporate Legal',
    clientEmail: 'gsoto@highlandlogistics.com',
    clientPhone: '(858) 555-0910',
    assignedServerName: 'Elena Chen',
    assignedServerPhone: '(310) 555-9014',
    createdAt: '2026-09-10T09:00:00Z',
    updatedAt: '2026-09-13T16:00:00Z',
    deadlineDate: '2026-09-15',
    attempts: [
      {
        id: 'att-105-1',
        orderId: 'ord-105',
        timestamp: '2026-09-11T10:30:00Z',
        outcome: 'address_vacant',
        serverName: 'Elena Chen',
        serverBadgeId: 'OC-8821',
        latitude: 32.8795,
        longitude: -117.1472,
        locationAddress: '8840 Miramar Rd, Unit 14B, San Diego, CA 92126',
        notes: 'Commercial warehouse suite 14B completely cleared out. "Space Available for Lease" sign posted by Colliers. Neighboring business (Unit 14A) stated tenant vacated 3 months ago with no forwarding address.',
        photoUrl: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=600&q=80',
        verifiedGps: true
      },
      {
        id: 'att-105-2',
        orderId: 'ord-105',
        timestamp: '2026-09-13T15:45:00Z',
        outcome: 'bad_address',
        serverName: 'Elena Chen',
        serverBadgeId: 'OC-8821',
        latitude: 32.8796,
        longitude: -117.1470,
        locationAddress: '8840 Miramar Rd, Unit 14B, San Diego, CA 92126',
        notes: 'Follow-up inspection confirmed building manager has filed default judgment. Non-service declaration recommended for skip trace / diligence affidavit.',
        photoUrl: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=600&q=80',
        verifiedGps: true
      }
    ]
  }
];

export const INITIAL_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'notif-1',
    orderId: 'ord-101',
    caseNumber: 'CV-2026-08942',
    title: 'Service Completed Successfully! 🎯',
    message: 'Arthur Sterling was personally served at 1420 Ocean Ave, Penthouse 4B. GPS coordinates & physical description recorded.',
    channel: 'push',
    timestamp: '2026-09-14T17:36:00Z',
    read: false,
    priority: 'success'
  },
  {
    id: 'notif-2',
    orderId: 'ord-101',
    caseNumber: 'CV-2026-08942',
    title: 'Proof of Service Generated & Signed',
    message: 'Official Affidavit of Service signed under penalty of perjury by Server Marcus Vance #LA-4991. Ready for court e-filing.',
    channel: 'email',
    timestamp: '2026-09-14T17:46:00Z',
    read: false,
    priority: 'info'
  },
  {
    id: 'notif-3',
    orderId: 'ord-102',
    caseNumber: 'UD-2026-11409',
    title: 'Field Attempt Logged: No Answer',
    message: 'Attempt #2 logged by Elena Chen at 742 S Catalina Ave. Occupant suspected evading; preparing substituted service notice.',
    channel: 'push',
    timestamp: '2026-09-14T18:52:00Z',
    read: false,
    priority: 'warning'
  },
  {
    id: 'notif-4',
    orderId: 'ord-103',
    caseNumber: 'FAM-2026-04221',
    title: 'New Service Order Dispatched',
    message: 'Rush order assigned to Process Server Marcus Vance. Deadline: Sept 17.',
    channel: 'in_app',
    timestamp: '2026-09-14T16:22:00Z',
    read: true,
    priority: 'info'
  }
];
